version: '3.5'
services:
  glpi-db:
    image: mysql:8.0
    container_name: glpi-db
    restart: always
    #network_mode: host
    command:
      - mysqld
      - --port=3306  
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
      - --skip-character-set-client-handshake
      - --default-authentication-plugin=mysql_native_password
      - --max_connections=200
      - --mysqlx_max_connections=200   
    volumes:
      - ./mysql:/var/lib/mysql:rw
    environment:
      - MYSQL_DATABASE=glpi
      - MYSQL_USER=glpi
      - MYSQL_PASSWORD=glpi
      - MYSQL_ROOT_PASSWORD=root_pwd

  glpi-www:
    image: jackywn/glpi:latest
    container_name : glpi-www
    restart: always
    #network_mode: host
    ports:
      - "8000:80"
    volumes:
      - ./glpi:/app
      - /etc/hosts:/etc/hosts
    environment:
      - VERSION_GLPI=10.0.9
      - PHP_DATE_TIMEZONE=Asia/Shanghai
      - PHP_MEMORY_LIMIT=512M
      - PHP_MAX_EXECUTION_TIME=600
      - PHP_POST_MAX_SIZE=100M
      - PHP_UPLOAD_MAX_FILESIZE=50M
